### PR TITLE
Document CheriBSD breakage in 1.6 firmware release

### PR DESCRIPTION
**Pull request by jrtc27**

### CODE REVIEW

**Review by bsdjhb — APPROVED** [review]
I do wonder if we want a table of known versions and status / known caveats for each version?

**Review by kwitaszczyk — APPROVED** [review]

**Comment by brooksdavis** [comment]
Should we update this to 1.6.1 and commit it?

**Comment by rwatson** [comment]
Looks like this pull request requires a minor update, and then could be merged ..?

**Comment by brooksdavis** [comment]
I think we think the latest (1.7) is good and the instructions have become correct again?

**Comment by jrtc27** [comment]
Yes. We could document 1.6 as being broken, but I doubt anyone will end up on that version now if they aren't already on it.

**Pull request closed without merging**
