### PR TITLE
Use FAT32 for an SD card and simplify instructions for macOS

### PR DESCRIPTION
**Pull request by kwitaszczyk**

### CODE REVIEW

**Review by gvnn3 — APPROVED** [review]

**Comment by jrtc27** [comment]
If the FAT type doesn’t matter then it shouldn’t be specified at all so the default gets used

**Comment by kwitaszczyk** [comment]
> If the FAT type doesn’t matter then it shouldn’t be specified at all so the default gets used

In the proposed change, I do care that FAT32 is used and not FAT16 as I want to easily use an SD card larger than 4GB.

If we think that the default is always FAT32 on OSs we care about, I'd be fine with changing that.

**Comment by jrtc27** [comment]
> > If the FAT type doesn’t matter then it shouldn’t be specified at all so the default gets used
> 
> In the proposed change, I do care that FAT32 is used and not FAT16 as I want to easily use an SD card larger than 4GB.
> 
> If we think that the default is always FAT32 on OSs we care about, I'd be fine with changing that.

The default is whatever makes sense for that size (not all sizes even support all formats due to limitations on cluster size etc).

**Comment by kwitaszczyk** [comment]
@jrtc27 @brooksdavis Thanks! I wasn't aware that the default is what matches a size. Once I'm back in the lab next week, I'll test it on macOS and Linux, and then update the PR.

**Comment by kwitaszczyk** [comment]
I'll merge it now, and we can improve it separately, if needed.

**Pull request merged**
